# Site settings
title: DKKMA | ExpressionEngine Expert & Inbound Marketing Consultant
email: hellouk@dkkma.com
description: We are a creative design and development firm based in London, UK. We spezialize in developing complex ExpressionEngine based websites.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.dkkma.com" # the base hostname & protocol for your site
twitter_username: dkkma
github_username:  dkkma

permalink: /blog/entry/:title/

# img quick link
testimonial_img: /assets/images/testimonial/
project_img: /assets/images/projects/
blog_img: /assets/images/blog/
img: /assets/images/
svg: /assets/svg/
files: /assets/files/

category_archive:
  path: /blog/

# Collections
collections:
  - portfolio
  - services
  - testimonial
  - case-study
  - development

collections:
  portfolio:
    output: true
    permalink: /portfolio/entry/:title/
  services:
    output: true
    permalink: /services/:title/
  testimonial:
    output: true
    permalink: /testimonial/:title/
  development:
    output: true
    permalink: /dev/:title/

# Navigation
navigation:
 - title: Contact
   url: /contact/
 - title: Blog
   url: /blog/
 - title: About
   url: /about/
 - title: Portfolio
   url: /portfolio/
 - title: Services
   url: /services/

servicenav:
 - title: Web Design & Development
   url: /services/web-design-and-development/
 - title: ExpressionEngine Development
   url: /services/expressionengine-developer/
 - title: Inbound Marketing Consultation
   url: /services/inbound-marketing/

# Build settings
markdown: kramdown
include: [.htaccess]

gems:
  - jekyll-sitemap
