# Site settings
title: Full Service Inbound Marketing Agency - DKKMA
email: hellouk@dkkma.com
description: We are a full service inbound marketing agency based in London, UK. Work with us for web design, content marketing and lead nurturing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.dkkma.com" # the base hostname & protocol for your site
twitter_username: dkkma
github_username:  dkkma
production: true

permalink: /blog/entry/:title/

# img quick link
testimonial_img: /assets/images/testimonial/
project_img: /assets/images/projects/
inbound_img: /assets/images/inbound-marketing-glossary/
blog_img: /assets/images/blog/
dev_img: /assets/images/dev/
img: /assets/images/
svg: /assets/svg/
files: /assets/files/

category_archive:
  path: /blog/

# Collections
collections:
  - portfolio
  - services
  - testimonial
  - case-study
  - development

collections:
  portfolio:
    output: true
    permalink: /portfolio/entry/:title/
  services:
    output: true
    permalink: /services/:title/
  testimonial:
    output: true
    permalink: /testimonial/:title/
  development:
    output: true
    permalink: /dev/:title/
  inbound-marketing-glossary:
    output: true
    permalink: /inbound-marketing-glossary/:title/

# Navigation
navigation:
 - title: Services
   url: /services/
 - title: About
   url: /about/
 - title: Blog
   url: /blog/
 - title: Contact
   url: /contact/

servicenav:
 - title: Web Design & Development
   url: /services/custom-web-design-and-development/
 - title: ExpressionEngine Development
   url: /services/expressionengine-developer/
 - title: Inbound Marketing Consultation
   url: /services/inbound-marketing-consultation/

# Build settings
markdown: kramdown
include: ['.htaccess', '_offers']
exclude: ['s3_website.yml', 'divshot.json', 'gulpfile.js']

gems:
  - jekyll-sitemap
