# Site settings
title: DKKMA
email: hellouk@dkkma.com
description: Step inside the world of advertising, design and inbound marketing agency DKKMA, based in London, United Kingdom.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.dkkma.com" # the base hostname & protocol for your site
twitter_username: dkkma
github_username:  dkkma

permalink: /blog/entry/:title

# Blog index is outside of _blog
# paginate: 10
# paginate_path: "/blog/page/:num"

# img quick link
testimonial_img: https://dvxyu2dxv3uua.cloudfront.net/assets/images/testimonial/
project_img: https://dvxyu2dxv3uua.cloudfront.net/assets/images/projects/
blog_img: https://dvxyu2dxv3uua.cloudfront.net/assets/images/blog/
img: https://dvxyu2dxv3uua.cloudfront.net/assets/images/

category_archive:
  path: /blog/

# Collections
collections:
  - portfolio
  - services
  - testimonial

collections:
  portfolio:
    output: true
    permalink: /portfolio/entry/:title/
  services:
    output: true
    permalink: /services/:title/
  testimonial:
    output: true
    permalink: /testimonial/:title/

# Navigation
navigation:
 - title: Contact
   url: /contact
 - title: Testimonial
   url: /testimonial
 - title: Blog
   url: /blog
 - title: About
   url: /about
 - title: Portfolio
   url: /portfolio
 - title: Services
   url: /services

servicenav:
 - title: Web Design
   url: /services/web-design
 - title: eCommerce
   url: /services/ecommerce
 - title: Packaging
   url: /services/packaging
 - title: Newsletter
   url: /services/newsletter
 - title: Advertisement
   url: /services/advertisement

# Build settings
markdown: kramdown
include: [.htaccess]

gems:
  - jekyll-sitemap
